- name: "✨ Enhancement"
  description: "New feature or request"
  color: "eeff00"
- name: "🐛 Bug"
  description: "Something isn't working as intended"
  color: "ff4545"
- name: "⚠️ Mistake"
  description: "Mistake that doesn't influence usability"
  color: "ff4545"
- name: "🚑️ Hotfix"
  description: "Critical or emergency fix"
  color: "b60205"
- name: "🔒️ Security"
  description: "Address security vulnerabilities"
  color: "b60205"
- name: "📌 Dependencies"
  description: "External library or package updates"
  color: "4da0ff"
- name: "📝 Documentation"
  description: "Improvements or additions to documentation"
  color: "005999"
- name: "♻️ Refactor"
  description: "Code improvements without changing function"
  color: "009600"
- name: "🧪 Testing"
  description: "Add or improve tests"
  color: "00ff15"
- name: "💄 UI/UX"
  description: "Changes related to the user interface and experience"
  color: "ff2590"
- name: "👷 CI/CD"
  description: "Changes related to continuous integration/deployment"
  color: "00fff0"
- name: "🔧 Configuration"
  description: "Changes to configuration files or settings"
  color: "868686"
- name: "🛠️ Maintenance"
  description: "General maintenance and updates"
  color: "545454"
- name: "⚗️ Request Build"
  description: "Requests a build"
  color: "00ff9d"
- name: "🧐 Size Analysis"
  description: "Request for size analysis of the APK (only alongside a build request)"
  color: "00a164"
- name: "💬 Discussion"
  description: "Open discussion or brainstorming"
  color: "6f22ff"
- name: "❓ Question"
  description: "Further information is requested"
  color: "a16eff"
- name: "❌ Wontfix"
  description: "This will not be worked on"
  color: "ffffff"
- name: "🔄 Duplicate"
  description: "This issue or pull request already exists"
  color: "bbbbbb"
- name: "🚧 Work in Progress"
  description: "This is not yet complete"
  color: "ffa500"
