name: Actionlint

on:
  push:
    paths: [.github/workflows/**]

jobs:
  run:
    uses: RubberDuckCrew/.github/.github/workflows/action-actionlint.yml@845e392790542cd3f46c65785222e341b4d2f0e1 # v2.4.1
