name: Actionlint

on:
  push:
    paths: [.github/workflows/**]

jobs:
  run:
    uses: RubberDuckCrew/.github/.github/workflows/action-actionlint.yml@9359cf3f39584573a76ae17b2efc76b192c5050e # v2.3.0
