name: Add to project

on:
  issues:
    types: [opened]

jobs:
  run:
    uses: RubberDuckCrew/.github/.github/workflows/action-add-project.yml@0968afd074c1d7ee5654414dc45027fc9c35d8d3 # v1
    secrets: inherit
