name: Build APK & App Bundle

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write
env:
  FLUTTER_CHANNEL: "stable"
  PROPERTIES_PATH: "./app/android/key.properties"

jobs:
  build:
    name: Build APK & App Bundle
    runs-on: ubuntu-latest

    steps:
      - name: Checkout App Repository
        uses: actions/checkout@v4
        with:
          path: app
          ref: ${{ github.ref_name }}

      - name: Clone Package Repository
        uses: actions/checkout@v4
        with:
          repository: RubberDuckCrew/github_flutter
          path: github_flutter

      - uses: subosito/flutter-action@v2
        with:
          channel: ${{ env.FLUTTER_CHANNEL }}
          flutter-version: ${{ vars.FLUTTER_VERSION }}
          cache: true

      - name: Install dependencies
        working-directory: app
        run: flutter pub get

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set up keystore
        run: |
          echo keyPassword=\${{ secrets.KEY_STORE }} > ${{env.PROPERTIES_PATH}}
          echo storePassword=\${{ secrets.KEY_PASSWORD }} >> ${{env.PROPERTIES_PATH}}
          echo keyAlias=\${{ secrets.KEY_ALIAS }} >> ${{env.PROPERTIES_PATH}}
          echo "${{ secrets.KEYSTORE2 }}" | base64 --decode > app/android/app/key.jks

      - name: Prepare version name
        id: version_name
        run: echo "version_name=$(echo "${{github.ref_name}}" | tr / _)" >> $GITHUB_OUTPUT

      - name: Set build args
        run: echo "BUILD_ARGS=--release --flavor production --dart-define=GIT_COMMIT=${{ github.sha }}" >> $GITHUB_ENV

      - name: Build APK
        working-directory: app
        run: flutter build apk $BUILD_ARGS

      - name: Build App Bundle
        working-directory: app
        run: flutter build appbundle $BUILD_ARGS

      - name: Rename APK & App Bundle
        working-directory: app
        run: |
          mv build/app/outputs/flutter-apk/app-production-release.apk build/app/outputs/flutter-apk/GitDone_${{ steps.version_name.outputs.version_name }}.apk
          mv build/app/outputs/bundle/productionRelease/app-production-release.aab build/app/outputs/bundle/productionRelease/GitDone_${{ steps.version_name.outputs.version_name }}.aab

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: GitDone_${{ steps.version_name.outputs.version_name }}.apk
          path: app/build/app/outputs/flutter-apk/GitDone_${{ steps.version_name.outputs.version_name }}.apk

      - name: Upload App Bundle
        uses: actions/upload-artifact@v4
        with:
          name: GitDone_${{ steps.version_name.outputs.version_name }}.aab
          path: app/build/app/outputs/bundle/productionRelease/GitDone_${{ steps.version_name.outputs.version_name }}.aab

      - name: Release Artifacts
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            app/build/app/outputs/flutter-apk/GitDone_${{ steps.version_name.outputs.version_name }}.apk
            app/build/app/outputs/bundle/productionRelease/GitDone_${{ steps.version_name.outputs.version_name }}.aab