name: Close Actions

on:
  issues:
    types: [closed]
  pull_request:
    types: [closed]

jobs:
  run:
    uses: RubberDuckCrew/.github/.github/workflows/action-close-actions.yml@f6f2f76c549b7a82aafccde367f33d09c7cf0eae # v2.1.1
    permissions:
      issues: write
      pull-requests: write
      actions: write
