name: Close Actions

on:
  issues:
    types: [ closed ]
  pull_request:
    types: [ closed ]

jobs:
  close-actions:
    name: Close actions
    runs-on: ubuntu-latest

    permissions:
      issues: write
      pull-requests: write

    steps:
      - name: Remove labels
        uses: IamPekka058/removeLabels@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: "🚧 Work in Progress"
