name: Close Actions

on:
  issues:
    types: [closed]
  pull_request:
    types: [closed]

jobs:
  run:
    uses: RubberDuckCrew/.github/.github/workflows/action-close-actions.yml@56e4f827ad3706fe96a060b0aae589f9e2dd5c30 # v2.1.0
    permissions:
      issues: write
      pull-requests: write
      actions: write
