name: Close Actions

on:
  issues:
    types: [closed]
  pull_request:
    types: [closed]

jobs:
  run:
    uses: RubberDuckCrew/.github/.github/workflows/action-close-actions.yml@44514881ffd4d4403f96b145e1438af5d93d47f4 # v2.2.1
    permissions:
      issues: write
      pull-requests: write
      actions: write
