name: Enforce conventions

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]

jobs:
  run:
    uses: RubberDuckCrew/.github/.github/workflows/action-conventions.yml@f6f2f76c549b7a82aafccde367f33d09c7cf0eae # v2.1.1
    permissions:
      issues: write
      pull-requests: write
