name: Enforce conventions

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]

jobs:
  run:
    uses: RubberDuckCrew/.github/.github/workflows/action-conventions.yml@44514881ffd4d4403f96b145e1438af5d93d47f4 # v2.2.1
    permissions:
      issues: write
      pull-requests: write
