name: Build and deploy docs

on:
  push:
    branches: [main]
    paths: [docs/**, .github/workflows/docs.yml]
  pull_request:
    types: [opened, labeled, synchronize]
    paths: [docs/**, .github/workflows/docs.yml]

jobs:
  run:
    uses: RubberDuckCrew/.github/.github/workflows/action-docs.yml@5a0a828ec10bcebf7c980d13fca16f99be69f6d0 # v2.4.0
    with:
      project-name: gitdone
    secrets:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
    permissions:
      contents: read
      deployments: write
      pull-requests: write
