name: Build and deploy docs

on:
  push:
    branches: [main]
    paths: [docs/**, .github/workflows/docs.yml]
  pull_request:
    types: [opened, labeled, synchronize]
    paths: [docs/**, .github/workflows/docs.yml]

jobs:
  run:
    uses: RubberDuckCrew/.github/.github/workflows/action-docs.yml@f6f2f76c549b7a82aafccde367f33d09c7cf0eae # v2.1.1
    with:
      project-name: gitdone
    secrets:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
    permissions:
      contents: read
      deployments: write
      pull-requests: write
