name: Build and deploy docs

on:
  push:
    branches: [ main ]
    paths: [ docs/**, .github/workflows/docs.yml ]
  pull_request:
    types: [ opened, labeled, synchronize ]
    paths: [ docs/**, .github/workflows/docs.yml ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    name: Build docs
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: docs

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: docs/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build with VitePress
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: docs-dist
          path: docs/.vitepress/dist

  deploy:
    name: Deploy docs
    needs: build
    if: ${{ ( github.ref == 'refs/heads/main' || contains(github.event.pull_request.labels.*.name, '⚗️ Request Build') ) && !github.event.pull_request.head.repo.fork}}
    runs-on: ubuntu-latest

    permissions:
      contents: read
      deployments: write
      pull-requests: write

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v5
        with:
          name: docs-dist
          path: dist

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        id: deploy
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          command: pages deploy dist --project-name=gitdone --branch=${{ github.head_ref || github.ref_name }}

      - name: Comment deployment info
        uses: thollander/actions-comment-pull-request@v3
        if: github.event_name == 'pull_request'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          comment-tag: deployment-info
          mode: recreate
          message: |
              **🌐 Preview Deployment**
              - ${{ steps.deploy.outputs.pages-deployment-alias-url }}

      - name: Remove build request label
        uses: IamPekka058/removeLabels@v2
        if: github.event_name == 'pull_request'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: |
              - ⚗️ Request Build
