name: Build and deploy docs

on:
  push:
    branches: [main]
    paths: [docs/**, .github/workflows/docs.yml]
  pull_request:
    types: [opened, labeled, synchronize]
    paths: [docs/**, .github/workflows/docs.yml]

jobs:
  run:
    uses: RubberDuckCrew/.github/.github/workflows/action-docs.yml@44514881ffd4d4403f96b145e1438af5d93d47f4 # v2.2.1
    with:
      project-name: gitdone
    secrets:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
    permissions:
      contents: read
      deployments: write
      pull-requests: write
