name: Enforce labels

on:
  pull_request_target:
    types: [ opened, labeled, unlabeled, synchronize ]

jobs:
  enforce-labels:
    name: Enforce pull request labels
    runs-on: ubuntu-latest

    permissions:
      issues: write
      pull-requests: write

    steps:
      - uses: mheap/github-action-required-labels@v5
        with:
          mode: minimum
          count: 1
          labels: "*"
          use_regex: true
          add_comment: true
          message: "You need to assign at least one label before merging this pull request."