name: Sync labels

on:
  schedule:
    - cron: "0 3 * * 0"
  workflow_dispatch:

jobs:
  run:
    uses: RubberDuckCrew/.github/.github/workflows/action-sync-labels.yml@44514881ffd4d4403f96b145e1438af5d93d47f4 # v2.2.1
    permissions:
      issues: write
    with:
      additional-config: ".github/labels.yml"
