name: Sync webhook

on:
  schedule:
    - cron: "0 3 * * 0"
  push:
    branches: [main]
    paths: [.github/workflows/sync-webhook.yml]
  workflow_dispatch:

jobs:
  run:
    uses: RubberDuckCrew/.github/.github/workflows/action-sync-webhook.yml@f6f2f76c549b7a82aafccde367f33d09c7cf0eae # v2.1.1
    with:
      bot-app-id: ${{ vars.RUBBERDUCKCREW_BOT_APP_ID }}
    secrets:
      BOT_APP_PRIVATE_KEY: ${{ secrets.RUBBERDUCKCREW_BOT_APP_PRIVATE_KEY }}
      WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
