name: Sync labels

on:
  schedule:
    - cron: "0 3 * * 0"
  workflow_dispatch:

jobs:
  run:
    uses: RubberDuckCrew/.github/.github/workflows/action-sync-labels.yml@f6f2f76c549b7a82aafccde367f33d09c7cf0eae # v2.1.1
    permissions:
      issues: write
    with:
      additional-config: ".github/labels.yml"
