name: Test, Build and Release
run-name: Test, Build and Release ${{ inputs.release-version }}

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, labeled, synchronize]
  workflow_dispatch:
    inputs:
      build-type:
        description: 'Type of build to perform'
        required: true
        default: 'release'
        type: choice
        options:
          - build
          - size-analysis
          - release
      release-version:
        description: 'The version to release (e.g., 1.2.3). The "v" prefix is added automatically.'
        required: false
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  main:
    uses: RubberDuckCrew/flutter-action/.github/workflows/test-build-release.yml@main

    with:
      app-name: 'GitDone'
      working-directory: '.'
      build-type: ${{ github.event.inputs.build-type || 'test' }}
      release-version: ${{ github.event.inputs.release-version }}
      java-version: '21'
      bot-app-id: ${{ vars.RUBBERDUCKCREW_BOT_APP_ID }}

    secrets:
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
      KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
      BOT_APP_PRIVATE_KEY: ${{ secrets.RUBBERDUCKCREW_BOT_APP_PRIVATE_KEY }}